export type Lang = "es" | "en";

export const content = {
  es: {
    nav: {
      rooms: "Habitaciones",
      tours: "Tours",
      location: "Cómo llegar",
      contact: "Contacto",
      bookNow: "Reservar",
    },
    hero: {
      tagline: "Tu base en el Caribe.",
      taglineAlt: "Your Caribbean Base.",
      subtitle: "Descanso real, aventuras épicas. Santa Marta, Colombia.",
      bookNow: "Reservar Ahora",
      seeRooms: "Ver Habitaciones",
    },
    why: {
      heading: "Por qué La Guaca",
      items: [
        {
          icon: "MapPin",
          title: "Ubicación perfecta",
          desc: "Barrio Bavaria, a 5 min del centro histórico y con acceso fácil a todo.",
        },
        {
          icon: "Waves",
          title: "Piscina jacuzzi",
          desc: "Refresca el cuerpo después de explorar. Nuestra piscina es el corazón del hostal.",
        },
        {
          icon: "Coffee",
          title: "Desayuno incluido",
          desc: "Arranca el día con energía. Desayuno casero gratuito para todos los huéspedes.",
        },
        {
          icon: "Compass",
          title: "Base de exploración",
          desc: "Tayrona, Minca, Ciudad Perdida. Organizamos tours y te contamos todo.",
        },
      ],
    },
    rooms: {
      heading: "Habitaciones",
      subheading: "Desde la cama compartida hasta la privada con vista. Algo para cada viajero.",
      fromPrice: "Desde",
      night: "/ noche",
      bookRoom: "Reservar",
      seeAll: "Ver todas las habitaciones",
      items: [
        {
          id: "dorm-mixed",
          name: "Dormitorio Mixto",
          capacity: "6-8 personas",
          price: "COP 55.000",
          priceUSD: "USD 13",
          img: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&auto=format&fit=crop&q=80",
          amenities: ["Taquilla", "Ventilador", "Baño compartido", "Desayuno incluido"],
          tag: "Más popular",
        },
        {
          id: "dorm-female",
          name: "Dormitorio Femenino",
          capacity: "4-6 personas",
          price: "COP 60.000",
          priceUSD: "USD 14",
          img: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&auto=format&fit=crop&q=80",
          amenities: ["Solo mujeres", "Taquilla", "Ventilador", "Desayuno incluido"],
          tag: null,
        },
        {
          id: "private-double",
          name: "Privada Doble",
          capacity: "2 personas",
          price: "COP 160.000",
          priceUSD: "USD 38",
          img: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&auto=format&fit=crop&q=80",
          amenities: ["Cama doble", "AC", "Baño privado", "Desayuno incluido"],
          tag: "Confort",
        },
      ],
    },
    services: {
      heading: "Todo lo que necesitas",
      items: [
        { icon: "Waves", label: "Piscina Jacuzzi" },
        { icon: "Coffee", label: "Desayuno gratis" },
        { icon: "Wifi", label: "Fibra óptica" },
        { icon: "Monitor", label: "Coworking" },
        { icon: "Shirt", label: "Lavandería" },
        { icon: "Car", label: "Taxi al aeropuerto" },
        { icon: "Shield", label: "Consigna de equipaje" },
        { icon: "Users", label: "Área social 24h" },
      ],
    },
    destinations: {
      heading: "Tu base para explorar",
      subheading: "Todo el Caribe colombiano a tu alcance desde La Guaca.",
      items: [
        {
          name: "Parque Tayrona",
          desc: "Jungla tropical + playas vírgenes. Un día que no vas a olvidar.",
          duration: "1 día",
          img: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&auto=format&fit=crop&q=80",
        },
        {
          name: "Minca",
          desc: "El pueblo de montaña más chévere de la Sierra Nevada.",
          duration: "1-2 días",
          img: "https://images.unsplash.com/photo-1592861956120-e524fc739696?w=800&auto=format&fit=crop&q=80",
        },
        {
          name: "Ciudad Perdida",
          desc: "El trek más épico de Colombia. 4-6 días en la selva.",
          duration: "4-6 días",
          img: "https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800&auto=format&fit=crop&q=80",
        },
        {
          name: "Taganga",
          desc: "Buceo, pescado fresco y puestas de sol con vista al mar.",
          duration: "Medio día",
          img: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80",
        },
        {
          name: "Playa Blanca",
          desc: "La playa que enamora. Aguas turquesas y arena blanca.",
          duration: "1 día",
          img: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
        },
      ],
    },
    reviews: {
      heading: "Lo que dicen los viajeros",
      score: "9.2 / 10",
      platform: "Hostelworld",
      items: [
        {
          name: "Julia M.",
          country: "Alemania",
          rating: 10,
          text: "El mejor hostal de Santa Marta. La piscina, el desayuno y el ambiente son increíbles. Volveré seguro.",
        },
        {
          name: "Tom R.",
          country: "Australia",
          rating: 9,
          text: "Perfect base to explore the Caribbean coast. Staff helped us organize the Tayrona tour and Ciudad Perdida trek. Highly recommended!",
        },
        {
          name: "Ana C.",
          country: "España",
          rating: 10,
          text: "Me quedé 5 días y hubiera seguido más. El jacuzzi al atardecer, el ambiente social y la ubicación son imbatibles.",
        },
        {
          name: "Carlos V.",
          country: "Colombia",
          rating: 9,
          text: "Excelente calidad-precio. Nada le falta: WiFi rápido, desayuno rico, camas cómodas y el staff es muy atento.",
        },
      ],
    },
    tours: {
      heading: "Tours desde La Guaca",
      subheading: "Organizamos todo para que solo tengas que llegar.",
      seeAll: "Ver todos los tours",
      items: [
        {
          id: "tayrona",
          name: "Parque Tayrona",
          duration: "1 día",
          difficulty: "Moderado",
          price: "COP 120.000",
          img: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&auto=format&fit=crop&q=80",
        },
        {
          id: "minca",
          name: "Minca Day Trip",
          duration: "1 día",
          difficulty: "Fácil",
          price: "COP 80.000",
          img: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&auto=format&fit=crop&q=80",
        },
        {
          id: "ciudad-perdida",
          name: "Ciudad Perdida Trek",
          duration: "4-6 días",
          difficulty: "Difícil",
          price: "COP 1.200.000",
          img: "https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800&auto=format&fit=crop&q=80",
        },
      ],
    },
    footer: {
      address: "Barrio Bavaria, Santa Marta, Colombia",
      phone: "+57 300 000 0000",
      email: "hola@laguacahostel.com",
      rights: "La Guaca Hostel. Todos los derechos reservados.",
    },
    cta: {
      bookNow: "Reservar Ahora",
      whatsapp: "Escribir por WhatsApp",
      askTour: "Consultar Tour",
    },
  },
  en: {
    nav: {
      rooms: "Rooms",
      tours: "Tours",
      location: "How to Get Here",
      contact: "Contact",
      bookNow: "Book Now",
    },
    hero: {
      tagline: "Your Caribbean Base.",
      taglineAlt: "Tu base en el Caribe.",
      subtitle: "Real comfort, epic adventures. Santa Marta, Colombia.",
      bookNow: "Book Now",
      seeRooms: "See Rooms",
    },
    why: {
      heading: "Why La Guaca",
      items: [
        {
          icon: "MapPin",
          title: "Perfect Location",
          desc: "Bavaria neighborhood, 5 min from the historic center with easy access to everything.",
        },
        {
          icon: "Waves",
          title: "Jacuzzi Pool",
          desc: "Cool off after exploring. Our pool is the heart of the hostel.",
        },
        {
          icon: "Coffee",
          title: "Free Breakfast",
          desc: "Start your day with energy. Homemade breakfast included for all guests.",
        },
        {
          icon: "Compass",
          title: "Explorer's Base",
          desc: "Tayrona, Minca, Lost City. We organize tours and tell you everything.",
        },
      ],
    },
    rooms: {
      heading: "Rooms",
      subheading: "From shared dorms to private rooms. Something for every traveler.",
      fromPrice: "From",
      night: "/ night",
      bookRoom: "Book",
      seeAll: "See all rooms",
      items: [
        {
          id: "dorm-mixed",
          name: "Mixed Dorm",
          capacity: "6-8 people",
          price: "COP 55,000",
          priceUSD: "USD 13",
          img: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&auto=format&fit=crop&q=80",
          amenities: ["Locker", "Fan", "Shared bathroom", "Breakfast included"],
          tag: "Most popular",
        },
        {
          id: "dorm-female",
          name: "Female Dorm",
          capacity: "4-6 people",
          price: "COP 60,000",
          priceUSD: "USD 14",
          img: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&auto=format&fit=crop&q=80",
          amenities: ["Women only", "Locker", "Fan", "Breakfast included"],
          tag: null,
        },
        {
          id: "private-double",
          name: "Private Double",
          capacity: "2 people",
          price: "COP 160,000",
          priceUSD: "USD 38",
          img: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&auto=format&fit=crop&q=80",
          amenities: ["Double bed", "AC", "Private bathroom", "Breakfast included"],
          tag: "Comfort",
        },
      ],
    },
    services: {
      heading: "Everything You Need",
      items: [
        { icon: "Waves", label: "Jacuzzi Pool" },
        { icon: "Coffee", label: "Free Breakfast" },
        { icon: "Wifi", label: "Fiber Optic WiFi" },
        { icon: "Monitor", label: "Coworking Space" },
        { icon: "Shirt", label: "Laundry" },
        { icon: "Car", label: "Airport Taxi" },
        { icon: "Shield", label: "Luggage Storage" },
        { icon: "Users", label: "Social Area 24h" },
      ],
    },
    destinations: {
      heading: "Your Base to Explore",
      subheading: "The entire Colombian Caribbean coast within reach from La Guaca.",
      items: [
        {
          name: "Tayrona Park",
          desc: "Tropical jungle + pristine beaches. A day you won't forget.",
          duration: "1 day",
          img: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&auto=format&fit=crop&q=80",
        },
        {
          name: "Minca",
          desc: "The coolest mountain village in the Sierra Nevada.",
          duration: "1-2 days",
          img: "https://images.unsplash.com/photo-1592861956120-e524fc739696?w=800&auto=format&fit=crop&q=80",
        },
        {
          name: "Lost City",
          desc: "Colombia's most epic trek. 4-6 days in the jungle.",
          duration: "4-6 days",
          img: "https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800&auto=format&fit=crop&q=80",
        },
        {
          name: "Taganga",
          desc: "Diving, fresh fish and sunsets overlooking the sea.",
          duration: "Half day",
          img: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80",
        },
        {
          name: "Playa Blanca",
          desc: "The beach that steals your heart. Turquoise waters and white sand.",
          duration: "1 day",
          img: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
        },
      ],
    },
    reviews: {
      heading: "What Travelers Say",
      score: "9.2 / 10",
      platform: "Hostelworld",
      items: [
        {
          name: "Julia M.",
          country: "Germany",
          rating: 10,
          text: "Best hostel in Santa Marta. The pool, breakfast and vibe are incredible. Definitely coming back.",
        },
        {
          name: "Tom R.",
          country: "Australia",
          rating: 9,
          text: "Perfect base to explore the Caribbean coast. Staff helped us organize the Tayrona tour and Ciudad Perdida trek. Highly recommended!",
        },
        {
          name: "Ana C.",
          country: "Spain",
          rating: 10,
          text: "I stayed 5 days and could have stayed longer. The jacuzzi at sunset, the social vibe and location are unbeatable.",
        },
        {
          name: "Carlos V.",
          country: "Colombia",
          rating: 9,
          text: "Excellent value for money. Nothing is missing: fast WiFi, delicious breakfast, comfortable beds and very attentive staff.",
        },
      ],
    },
    tours: {
      heading: "Tours from La Guaca",
      subheading: "We organize everything so you just have to show up.",
      seeAll: "See all tours",
      items: [
        {
          id: "tayrona",
          name: "Tayrona Park",
          duration: "1 day",
          difficulty: "Moderate",
          price: "COP 120,000",
          img: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&auto=format&fit=crop&q=80",
        },
        {
          id: "minca",
          name: "Minca Day Trip",
          duration: "1 day",
          difficulty: "Easy",
          price: "COP 80,000",
          img: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&auto=format&fit=crop&q=80",
        },
        {
          id: "ciudad-perdida",
          name: "Lost City Trek",
          duration: "4-6 days",
          difficulty: "Hard",
          price: "COP 1,200,000",
          img: "https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800&auto=format&fit=crop&q=80",
        },
      ],
    },
    footer: {
      address: "Bavaria Neighborhood, Santa Marta, Colombia",
      phone: "+57 300 000 0000",
      email: "hello@laguacahostel.com",
      rights: "La Guaca Hostel. All rights reserved.",
    },
    cta: {
      bookNow: "Book Now",
      whatsapp: "Message on WhatsApp",
      askTour: "Ask About Tour",
    },
  },
};
